### ISSUE TITLE
Como passar VARSAI quando temos mais de uma equação diferencial

### ISSUE THREAD

**Issue by marciobez** [iurisegtovich/estimation#4]
Prezado Iuri, andei testando seu código, muito bom. Gostaria de saber como retornar a VARSAI quando temos um sistema de equações diferenciais. Tive a impressão que VARSAI só aceita retornar vetores, como faço para retornar matrizes contendo valores calculados para y1, y2, e y3, por exemplo?
Agradeço demais a atenção
Marcio

**Comment by iurisegtovich** [comment]
olá,
imagino q você esteja olhando para o exemplo "estimation_examples/tank_dynamics/main.f90",

nesse exemplo o arquivo de dados experimentais está formatado como um único experimento (uma linha da tabela de dados) com 10 especificações (10 tempos) e 10 medidas (medidas de y1 em 10 instantes de tempo distintos)

em cada experimento, a variável VARSAI é um vetor com 1 dimensão, esse é o formato de dados usado no processamento alǵebrico dos dados .

a forma mais direta de usar esse código para trabalhar com 4 diferentes tipos de medidas, é montar um vetor VARSAI com tamanho ny1+ny2+ny3+ny4

então de VARSAI(1) até VARSAI(ny1) corresponde às medidas de y1
de então de VARSAI(ny1+1) até VARSAI(ny1+ny2) corresponde às medidas de y2
e assim sucessivamente.

você também pode estender o vetor VARENT caso y1,y2,y3 e y4 não tenham sido medidos nos mesmos valores da sua coordenada de integração, e para incorporar outras variáveis de contorno ou condições iniciais fixadas que tenham sido mudadas de um experimento para outro.

**Comment by marciobez** [comment]
Sim, eu "concatenei" as colunas da matriz de 3 colunas (y1,y2,y3, 30 elementos cada) numa coluna/vetor única. Fiz isso, mas VARSAI só está retornando um vetor de tamanho igual ao número de variáveis de saída = 3.
Acho que o problema está na formatação do arquivo de leitura de dados experimentais. No exemplo que estou fazendo, ele tem essa cara abaixo. Fazendo assim, VARSAI só aceita 3 elementos e não 90 (30*3). Se eu alimentar os 90 elementos calculados, o programa retorna o seguinte erro:
**Program received signal SIGSEGV: Segmentation fault - invalid memory reference**

Seria essa a forma de ler os dados? Agradeço a atenção

> LEITURA DE (NMOD)
1
> LEITURA DE (NEXP, NVENT, NVSAI) DO MODELO
30 1 3
> LEITURA DE (X1, X2, ..., Y1, VAR1, Y2, VAR2, ...)
0.000000e+00 1.000000e+00	0.0500	0.000000e+00	0.0500	0.000000e+00	0.0500
1.379310e-01	8.416309e-01	0.0500	1.471287e-01	0.0500	1.124041e-02	0.0500
2.758621e-01	7.083425e-01	0.0500	2.511197e-01	0.0500	4.053781e-02	0.0500
4.137931e-01	5.961629e-01	0.0500	3.214792e-01	0.0500	8.235794e-02	0.0500
5.517241e-01	5.017491e-01	0.0500	3.658473e-01	0.0500	1.324036e-01	0.0500
6.896552e-01	4.222875e-01	0.0500	3.903424e-01	0.0500	1.873701e-01	0.0500
8.275862e-01	3.554102e-01	0.0500	3.998437e-01	0.0500	2.447461e-01	0.0500
9.655172e-01	2.991242e-01	0.0500	3.982245e-01	0.0500	3.026514e-01	0.0500
1.103448e+00	2.517521e-01	0.0500	3.885422e-01	0.0500	3.597057e-01	0.0500
1.241379e+00	2.118824e-01	0.0500	3.731956e-01	0.0500	4.149220e-01	0.0500
1.379310e+00	1.783267e-01	0.0500	3.540522e-01	0.0500	4.676211e-01	0.0500
1.517241e+00	1.500853e-01	0.0500	3.325528e-01	0.0500	5.173619e-01	0.0500
1.655172e+00	1.263164e-01	0.0500	3.097971e-01	0.0500	5.638865e-01	0.0500
1.793103e+00	1.063118e-01	0.0500	2.866124e-01	0.0500	6.070759e-01	0.0500
1.931034e+00	8.947527e-02	0.0500	2.636104e-01	0.0500	6.469144e-01	0.0500
2.068966e+00	7.530515e-02	0.0500	2.412325e-01	0.0500	6.834623e-01	0.0500
2.206897e+00	6.337914e-02	0.0500	2.197871e-01	0.0500	7.168338e-01	0.0500
2.344828e+00	5.334184e-02	0.0500	1.994784e-01	0.0500	7.471798e-01	0.0500
2.482759e+00	4.489414e-02	0.0500	1.804311e-01	0.0500	7.746748e-01	0.0500
2.620690e+00	3.778429e-02	0.0500	1.627091e-01	0.0500	7.995066e-01	0.0500
2.758621e+00	3.180043e-02	0.0500	1.463304e-01	0.0500	8.218692e-01	0.0500
2.896552e+00	2.676422e-02	0.0500	1.312796e-01	0.0500	8.419561e-01	0.0500
3.034483e+00	2.252559e-02	0.0500	1.175172e-01	0.0500	8.599572e-01	0.0500
3.172414e+00	1.895824e-02	0.0500	1.049867e-01	0.0500	8.760551e-01	0.0500
3.310345e+00	1.595584e-02	0.0500	9.362077e-02	0.0500	8.904234e-01	0.0500
3.448276e+00	1.342892e-02	0.0500	8.334558e-02	0.0500	9.032255e-01	0.0500
3.586207e+00	1.130220e-02	0.0500	7.408399e-02	0.0500	9.146138e-01	0.0500
3.724138e+00	9.512279e-03	0.0500	6.575823e-02	0.0500	9.247295e-01	0.0500
3.862069e+00	8.005827e-03	0.0500	5.829168e-02	0.0500	9.337025e-01	0.0500
4.000000e+00	6.737951e-03	0.0500	5.161018e-02	0.0500	9.416519e-01	0.0500

**Comment by iurisegtovich** [comment]
nesse caso você estruturou seus dados em 30 experimentos com 3 medidas em cada.

aí a varsai vai ter tamanho 3 mesmo

e o seu modelo vai ser chamado 30 vezes dando um valor de x e recebendo 3 novos valores de y de cada vez

você poderia alternativamente estruturar como 1 experimento com 30 xizes e 90 ypsulons

então o arquivos de dados exp teria uma única linha com 120 colunas

seja qual for sua escolha, só precisa fazer seu modelo trabalhar com a mesma convenção que o dados exp

ou recebr 30x e retornar 90y em 1 exp
ou receber 1x e retornar 3y e repetir por 30 exps

**Comment by marciobez** [comment]
Iuri, eu coloquei tudo numa só coluna com 30+3x30+3x30 elementos, contando os dados de erros experimentais. O problema é que o código reclama que não consegue inverter a matriz dentro da GAUSSNEWTON pois `DABS(AUX)<1.D-10`. Além disso, o primeiro passo/modificação que o código dá nos parâmetros está como NaN.
Tem alguma ideia do que seja?

Na verdade, para mim, que venho do Octave/Scilab, organizar os dados em colunas como fiz acima é mais prático do que fazer tudo numa só coluna.

Observando a parte do código que lê os dados:

`DO K=1,NEXP(M)
READ(DADOSEXP_FNUM,*) (XE(M)%M(K,I),I=1,NENT(M)), (YE(M)%M(K,I),VARYE(M)%M(K,I,I),I=1,NSAI(M))
ENDDO`

Conferi que a leitura ocorre como esperado, mesmo os dados estando em colunas, o problema para mim é fazer VARSAI receber e retornar os Y's calculados. Poderia me informar onde preciso modificar?

Agradeço demais a atenção.

**Comment by iurisegtovich** [comment]
o método de Gauss Newton não está muito robusto nesse código.
sugiro conferir os resultados do enxame antes de se preocupar com o gauss newton (veja os arquivos que foram gerados antes do programa dar erro)

teoricamente você só precisaria montar o arquivo de dados exp q vc me mostrou e mexer no arquivo de modelo,

se quiser colocar o seu arquivo de modelo em comentário eu posso dar uma olhada (o arquivo main.f90 na pasta MODEL_src)

**Comment by marciobez** [comment]
program main
!-------------------------------------------------------------------------------
  use estimation_mod

  !use gnuplot_mod

  !-------------------------------------------------------------------------------
  call estimation(MODELS)     !  Faz a magica acontecer
  !call plot                   !  plota os resultados com os parametros estimados
  !pause                       

!-------------------------------------------------------------------------------
  CONTAINS
!===============================================================================
  SUBROUTINE MODELS(M,VARENT, VARSAI, PARAM, GUESS)
    INTEGER , INTENT(IN) :: M
    REAL(8), INTENT(IN) :: VARENT(:)
    REAL(8), INTENT(OUT) :: VARSAI(:)
    REAL(8), INTENT(IN) :: GUESS(:)
    REAL(8), INTENT(IN) :: PARAM(:)
    SELECT CASE(M)
    CASE(1)
    CALL MODEL_A(VARENT, VARSAI, PARAM, GUESS)
    ENDSELECT
   ENDSUBROUTINE
!===============================================================================
  SUBROUTINE MODEL_A(VARENT, VARSAI, PARAM, GUESS)
    REAL(8), INTENT(IN) :: VARENT(:)
    REAL(8), INTENT(OUT) :: VARSAI(:)
    REAL(8), INTENT(IN) :: GUESS(:)
    REAL(8) :: PARAM(:)
    INTEGER :: i, j, p
    integer, parameter :: NEQ=3, npontos=30, numPAR=2
    REAL(8) :: t_final, dt, t, Y(neq), dY(neq), YPRIME(neq), tOUT, tEND(npontos), y0(neq), resu(30,3),sai(90)
    !
    ! **** VARIAVEIS DA DASSL ***************************************
    INTEGER, parameter  :: LIW=20+neq, lrw=40+9*neq+neq*neq
    INTEGER :: INFO(15), IWORK(20+neq), idid, IPAR(1), ires(neq)
    REAL*8  :: RTOL(neq), ATOL(neq), RWORK(40+9*neq+neq*neq), RPAR(numPAR)
    IWORK=0; RWORK=0.D0; RPAR=0.D0; INFO=0; IDID=0; IPAR=0; RTOL=1.D-6; ATOL=1.D-8
! ***************************************************************
    !
    !
    !VARSAI(30,3)=0.d0
    t_final = 4.0d0
    !
    rpar(1) = PARAM(1)
    rpar(2) = PARAM(2)
    !
    Y = (/1.0d0, 0.0d0, 0.0d0/) !CONDICAO INICIAL
    y0 = Y
    yprime = (/1.0d0, -1.0d0, 0.0d0/)
    !yprime = dY
    !
    !ROTINA DE CHAMADA DA DASSL PARA INTEGRAÇÃO DO SISTEMA DE DAEs, EM PASSOS DE TEMPO DT, ATÉ O TEMPO FINAL TEND
    ! PA: an = a1 + r*(n-1) ===> r = (an - a1)/(n-1)

    dt = (t_final - 0.0d0)/real(npontos-1.d0)
    t = 0.0d0
    !tout = 0.d0
    !tEND=VARENT
    
    open(199,file='DASSL.dat',status='unknown')
    !open(200,file='varsai.dat',status='unknown'action='replace')
100 format(i2,1x,4(1x,F13.6))
101 format(5(E15.8,1x))
    tout = t + dt
    
    resu = 0.d0
    DO i=1,npontos
       !DO WHILE (t .NE. tEND(i))
        !write(*,*) i, t, tEND(i)
        !pause
        if (i .EQ. 1) then
            resu(i,1:3) = y0
            !write(*,101) resu(i,1:3), RPAR(1), RPAR(2)
            write(199,100) i, t, Y(1), Y(2), Y(3)!, RPAR(1), RPAR(2)
            !write(*,*) 'i=1'
        else
        CALL DDASSL (RES, NEQ, t, Y, YPRIME, tOUT, INFO, RTOL, ATOL, IDID, RWORK, LRW, IWORK, LIW, RPAR, IPAR, JAC)
        !INTEGRA O O SISTEMA
        !write(*,100) i, t, Y(1), Y(2), Y(3)!, RPAR(1), RPAR(2)
        write(199,100) i, t, Y(1), Y(2), Y(3)!, RPAR(1), RPAR(2)
        !pause
        !t = tOUT
        tOUT=t+dt
        !enddo
        resu(i,1:3) = y
        !write(*,101) resu(i,1:3), RPAR(1), RPAR(2)
        endif
    ENDDO
    varsai = y
    !write(*,*) varsai
    close(199)

!250 format(i2,3(1x,f15.6))
    !open(500,file='myreport.dat',status='unknown')
    p = 0
    do i=1,npontos
      DO j=1,neq
          p = p+1
          !write(200,101) resu(i,j)
          sai(p) = resu(i,j)
          !write(*,250) p, sai(p), RPAR(1), RPAR(2)
       enddo
       !pause
    enddo

    varsai = sai
    
    !close(200)
    !close(500)
    

  ENDSUBROUTINE
!===============================================================================
  SUBROUTINE RES(t,Y,YPRIME,DELTA,IRES,RPAR,IPAR)
    !FUNÇÃO RESIDUO PARA O SOLVER ALGEBRICO DIFERENCIAL DASSL
    real(8) :: t, Y(3), YPRIME(3), DELTA(3), RPAR(2)
    INTEGER :: IRES,IPAR(1)
    real(8) :: k1, k2, dydt(3)
    !
    dydt(1)=YPRIME(1)
    dydt(2)=YPRIME(2)
    dydt(3)=YPRIME(3)
    !
    k1=RPAR(1)
    k2=RPAR(2)
    !------------------------------------------
    delta(1) = k1*y(1) + dydt(1);
    delta(2) = k1*y(1) - k2*y(2) - dydt(2);
    delta(3) = k2*y(2) - dydt(3);
    !121 FORMAT(F6.4, 2X, F6.4, 2X, 3(2X,F9.5))
    !write(*,121) k1, k2, delta(1), delta(2), delta(3)
    !pause

  ENDSUBROUTINE
!===============================================================================
  SUBROUTINE JAC(t,Y,YPRIME,PD,CJ,RPAR,IPAR)
    !FUNÇÃO JACOBIANA PARA O SOLVER ALGEBRICO DIFERENCIAL DASSL
!O FORNECIMENTO DE UMA SUBROTINA PARA CALCULO DA JACOBIANA E NECESSARIO
!POIS A DASSL REQUER LINKAR ESSA ROTINA AO EXECUTÁVEL INDEPENDENTEMENTE DA INTENÇÃO DE USO
!QUE É DEFINIDA EM UMA DAS VARIÁVEIS INFO DELA
  real(8) t, Y(*), PD(*), CJ, YPRIME(*), RPAR(*)
  INTEGER IPAR(*)
!NO CASO DE USAR INFO INDICANDO QUE ELA NÃO VAI SER CHAMADA
!ELA DEVE SER DECLARADA AQUI MAS PODE FICAR SEM IMPLEMENTAÇÃO
  END SUBROUTINE
!===============================================================================
END PROGRAM

**Comment by marciobez** [comment]
[principal.zip](https://github.com/iurisegtovich/estimation/files/5934065/principal.zip)

**Comment by iurisegtovich** [comment]
veja em anexo duas opções

ou arquivo de dadosexp com 30 linhas em q o modelo é chamado 30 vezes, sempre integrando de zero até cada x

ou arquivo de dadosexp de 1 linha em q o modelo é chamado 1 vez e integra de 0 ate x1, depois de x1 ate x2... ate o x30 (mais eficiente)

> não rodei o código aqui, só fiz o esboço das linhas importantes marcadas com !#<--- blablabla

tem tb um script de python q eu usei para esse mudança de formato da tabela, que é uma coisa bem chata mesmo

[mbez.zip](https://github.com/iurisegtovich/estimation/files/5934244/mbez.zip)

**Comment by marciobez** [comment]
Iuri, a opção de leitura de dados em linha única  [principal_1linhas.zip](https://github.com/iurisegtovich/estimation/files/5934655/principal_1linhas.zip) rodou mas não houve convergência. A opção de colunas separadas estou vendo ainda, parece que há alguns problemas.
Estou anexando para que veja o resultado final na forma de gráfico, por alguma razão, o enxame não converge para a região de mínimo.
![myDAE](https://user-images.githubusercontent.com/46747229/107076581-60cc7980-67ca-11eb-8861-d5d3fcf86a40.png)
Muito obrigado pela ajuda.

**Comment by iurisegtovich** [comment]
deixa eu ver se fiz a conversão da tabela corretamente

[mbez_1linha_rev.zip](https://github.com/iurisegtovich/estimation/files/5934844/mbez_1linha_rev.zip)

acho q estava errado antes, agora o arquivo está como

`(x1) [x2] {x3} ... (y11 v11 y21 v21 y31 v31) [y12 v12 y22 v22 y32 v32] {...} ...`

e o código faz varsai(1)=y1; varsai(1)=y2; varsai(1)=y3
depois varsai(4)=y1; varsai(5)=y2; varsai(6)=y3
depois varsai(7)=y1; varsai(8)=y2; varsai(9)=y3
... até passar por todos os xizes

**Comment by marciobez** [comment]
Iuri, agora foi:
![myDAE](https://user-images.githubusercontent.com/46747229/107082598-2ca98680-67d3-11eb-9259-d6d0c5c02812.png)
No entanto, ainda não ficou claro como fazer no outro caso onde temos os dados organizados em tabelas. Poderia postar aqui um pouco mais de detalhe em como retornar a VARSAI pois ela vai continuar passando somente 3 elementos nessa configuração. Ou seria melhor focar as energias na conversão da tabela para uma única linha?
Muito grato.

**Comment by iurisegtovich** [comment]
[mbez_30linha_rev.zip](https://github.com/iurisegtovich/estimation/files/5935174/mbez_30linha_rev.zip)
fiz mais uma revisão no fortran para processar a estrutura de 30 linhas,
veja se está mais claro agora e se consegue obter o resultado esperado

da forma como o código do estimation está feito atualmente, a estratégia de 1 linha é mais eficiente pois o integrador é chamado para ir de x1 até x2, depois x2 ate x3 ... até x30 e te dá os resultados intermediários

no caso da tabela com 30 linhas, em cada linha nova o integrador integra desde zero até o valor de x1_linhaK

então esse código funciona mais eficieostpntemente com a estratégia de 1 linha, apesar de ser uma estrutura de dados confusa


nesse caso de 30 linhas,
var sai tem tamanho 3, e a função objetivo vai usar 30 termos de (varsai - yexp) * variancia * (varsai - yexp).Transposto
e a matriz de variancias vai ser uma matriz diagonal 3x3

no caso de 30 linhas, a função obj tem 1 unico termo no somatorio, mas esse termo é a operação matricial entre varsai com tamanho 90 e a matriz diagonal 90x90

os resultados devem ser perfeitmente equivalentes

**Comment by marciobez** [comment]
Mas como que a DASSL sabe os limites de integração? Está dando erro justamente nela, **erro 19**: `T = TOUT = 0`.
Grato

**Comment by iurisegtovich** [comment]
uhm, o primeiro x da sua tabela é zero né?

pode remover ele,
faz com 29 linhas

ele não contribui com a estimaçao se ele for só a própria condição inicial

aí o "primeiro experimento" vai ser a primeira medida após o início e não
vai dar esse erro

**Comment by marciobez** [comment]
Ah, você é o cara. Agora **foi que foi**! Eu vinha fazendo usando outros métodos de estimação (determinísticos? Tipo Nelder-Mead), no Octave (clone do MatLab) e em Python (usando o pacote assimulo - IDA solver).  IDA é concorrente da DASSL e foi recentemente incorporada ao MatLab. Comecei a usar Fortran recentemente pela velocidade, tirando vantagem que a Intel liberou o IFORT para download gratuito.
Enfim, é isso. Muito obrigado!

**Comment by iurisegtovich** [comment]
legal :D que bom!
